routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => 'auth'], function () {

    Route::get('/', function () {
        return view('home');
    });

    Route::get('home', 'App\Http\Controllers\HomeController@index')->name('home');
    Route::get('/', 'App\Http\Controllers\HomeController@index');
    Route::resource('wallets', 'App\Http\Controllers\WalletController');
    Route::resource('banks', 'App\Http\Controllers\BankController');
    Route::resource('credit_parcels', 'App\Http\Controllers\CreditParcelsController');
    Route::resource('expenses', 'App\Http\Controllers\ExpenseController');
    Route::resource('budgets', 'App\Http\Controllers\BudgetController');
    Route::resource('incomes', 'App\Http\Controllers\IncomeController');
    Route::resource('user_groups', 'App\Http\Controllers\UserGroupController');
    Route::resource('transfers', '\App\Http\Controllers\TransferController');
    Route::resource('investments', '\App\Http\Controllers\InvestmentController');
    Route::resource('invoices', '\App\Http\Controllers\InvoiceController');
    Route::resource('user', 'App\Http\Controllers\UserController', ['except' => ['show']]);
    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'App\Http\Controllers\ProfileController@edit']);
    Route::put('profile', ['as' => 'profile.update', 'uses' => 'App\Http\Controllers\ProfileController@update']);
    Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'App\Http\Controllers\ProfileController@password']);
    Route::post('profile/settings', ['as' => 'profile.settings', 'uses' => 'App\Http\Controllers\ProfileController@settings']);
    Route::get('{page}', ['as' => 'page.index', 'uses' => 'App\Http\Controllers\PageController@index']);
    Route::post('incomes/cancel_rec/{id}', 'App\Http\Controllers\IncomeController@cancel_rec')->name('incomes.cancel_rec');
    Route::get('incomes/confirm_recepit/{id}', 'App\Http\Controllers\IncomeController@confirm_recepit')->name('incomes.confirm_recepit');
    Route::get('user_groups/get_in/{group_id}/{user_id}', 'App\Http\Controllers\UserGroupController@GetInGroup')->name('user_groups.get_in');
    Route::get('user_groups/get_out/{group_id}/{user_id}', 'App\Http\Controllers\UserGroupController@GetOutGroup')->name('user_groups.get_out');
    Route::post('user_groups/remove_user/{group_id}/{user_id}', 'App\Http\Controllers\UserGroupController@remove_user')->name('user_groups.remove_user');
    Route::post('investments/insert_yield/{id}', 'App\Http\Controllers\InvestmentController@insert_yield')->name('investments.insert_yield');
    Route::post('budgets/default_budget', 'App\Http\Controllers\BudgetController@default_budget')->name('budgets.default_budget');
    Route::post('budgets/deactivate/{id}', 'App\Http\Controllers\BudgetController@disable')->name('budgets.disable');
    Route::post('budgets/reactivate/{id}', 'App\Http\Controllers\BudgetController@enable')->name('budgets.enable');
});

resources/views/layouts/navbars/sidebar.blade.php
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{{route('home')}}" class="brand-link">
        <img src="{{ asset('assets') }}/dist/img/moneymap_logo.png" alt="{{config('app.name')}}"
             class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">{{config('app.name')}}</span>
    </a>
    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{{ asset('assets') }}/dist/img/default-150x150.png" class="img-circle elevation-2"
                     alt="User Image">
            </div>
            <div class="info">
                <a href="{{route('profile.edit')}}" class="d-block">{{Auth::user()->name}}</a>
            </div>
        </div>
        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
                     with font-awesome or any other icon font library -->
                <li class="nav-item">
                    <a href="{{ route('home') }}" class="nav-link @if ($activePage == 'home') active @endif">
                        <i class="nav-icon fas fa-chart-bar"></i>
                        <p>{{ __('general.menu.dashboard') }}</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('expenses.index') }}"
                       class="nav-link @if ($activePage == 'expenses') active @endif">
                        <i class="nav-icon fas fa-arrow-down"></i>
                        <p>{{ __('general.menu.expenses') }}</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('incomes.index') }}"
                       class="nav-link @if ($activePage == 'incomes') active @endif">
                        <i class="nav-icon fas fa-arrow-up"></i>
                        <p>{{ __('general.menu.incomes') }}</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('transfers.index') }}"
                       class="nav-link @if ($activePage == 'transfers') active @endif">
                        <i class="nav-icon fas fa-money-bill-transfer"></i>
                        <p>{{ __('general.menu.transfers') }}</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('investments.index') }}"
                       class="nav-link @if ($activePage == 'investments') active @endif">
                        <i class="nav-icon fas fa-piggy-bank"></i>
                        <p>{{ __('general.menu.investments') }}</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('invoices.index') }}"
                       class="nav-link @if ($activePage == 'invoices') active @endif">
                        <i class="nav-icon fa-solid fa-file-invoice-dollar"></i>
                        <p>{{ __('general.menu.invoices') }}</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('wallets.index') }}"
                       class="nav-link @if ($activePage == 'wallets') active @endif">
                        <i class="nav-icon fa-solid fa-wallet"></i>
                        <p>{{ __("general.menu.wallets") }}</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('banks.index') }}"
                       class="nav-link @if ($activePage == 'banks') active @endif">
                        <i class="nav-icon fa-solid fa-building-columns"></i>
                        <p>{{ __("general.menu.banks") }}</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{route('budgets.index')}}"
                       class="nav-link @if ($activePage == 'budgets') active @endif">
                        <i class="nav-icon fa-solid fa-coins"></i>
                        <p>{{ __("general.menu.budget") }}</p>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>