routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => 'auth'], function () {

    Route::get('/', function () {
        return view('home');
    });

    Route::get('home', 'App\Http\Controllers\HomeController@index')->name('home');
    Route::get('/', 'App\Http\Controllers\HomeController@index');
    Route::resource('wallets', 'App\Http\Controllers\WalletController');
    Route::resource('banks', 'App\Http\Controllers\BankController');
    Route::resource('credit_parcels', 'App\Http\Controllers\CreditParcelsController');
    Route::resource('expenses', 'App\Http\Controllers\ExpenseController');
    Route::resource('budgets', 'App\Http\Controllers\BudgetController');
    Route::resource('incomes', 'App\Http\Controllers\IncomeController');
    Route::resource('user_groups', 'App\Http\Controllers\UserGroupController');
    Route::resource('transfers', '\App\Http\Controllers\TransferController');
    Route::resource('investments', '\App\Http\Controllers\InvestmentController');
    Route::resource('invoices', '\App\Http\Controllers\InvoiceController');
    Route::resource('user', 'App\Http\Controllers\UserController', ['except' => ['show']]);
    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'App\Http\Controllers\ProfileController@edit']);
    Route::put('profile', ['as' => 'profile.update', 'uses' => 'App\Http\Controllers\ProfileController@update']);
    Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'App\Http\Controllers\ProfileController@password']);
    Route::post('profile/settings', ['as' => 'profile.settings', 'uses' => 'App\Http\Controllers\ProfileController@settings']);
    Route::get('{page}', ['as' => 'page.index', 'uses' => 'App\Http\Controllers\PageController@index']);
    Route::post('incomes/cancel_rec/{id}', 'App\Http\Controllers\IncomeController@cancel_rec')->name('incomes.cancel_rec');
    Route::get('incomes/confirm_recepit/{id}', 'App\Http\Controllers\IncomeController@confirm_recepit')->name('incomes.confirm_recepit');
    Route::get('user_groups/get_in/{group_id}/{user_id}', 'App\Http\Controllers\UserGroupController@GetInGroup')->name('user_groups.get_in');
    Route::get('user_groups/get_out/{group_id}/{user_id}', 'App\Http\Controllers\UserGroupController@GetOutGroup')->name('user_groups.get_out');
    Route::post('user_groups/remove_user/{group_id}/{user_id}', 'App\Http\Controllers\UserGroupController@remove_user')->name('user_groups.remove_user');
    Route::post('investments/insert_yield/{id}', 'App\Http\Controllers\InvestmentController@insert_yield')->name('investments.insert_yield');
    Route::post('budgets/default_budget', 'App\Http\Controllers\BudgetController@default_budget')->name('budgets.default_budget');
    Route::post('budgets/deactivate/{id}', 'App\Http\Controllers\BudgetController@disable')->name('budgets.disable');
    Route::post('budgets/reactivate/{id}', 'App\Http\Controllers\BudgetController@enable')->name('budgets.enable');
});

resources/views/layouts/navbars/navs/auth.blade.php
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-dark">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="{{route('home')}}" class="nav-link">{{__('general.menu.dashboard')}}</a>
        </li>
    </ul>
    <ul class="navbar-nav ml-auto">
    <li class="nav-item dropdown">

            <a class="nav-link">
                <div id="clock">
                <b>{{\Carbon\Carbon::now()->setTimezone(\Illuminate\Support\Facades\Auth::user()->timezone->name)->format('H:i:s')}}</b>
                </div>
            </a>

    </li>
    </ul>
    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#" aria-expanded="false">
                @if(\Illuminate\Support\Facades\Auth::user()->language == 'pt_BR')
                <i class="flag-icon flag-icon-br"></i>
                @elseif(\Illuminate\Support\Facades\Auth::user()->language == 'en')
                <i class="flag-icon flag-icon-us"></i>
                @endif
            </a>
            <div class="dropdown-menu dropdown-menu-right p-0">
                <a href="#" class="dropdown-item @if(\Illuminate\Support\Facades\Auth::user()->language == 'pt_BR') active @endif">
                    <i class="flag-icon flag-icon-br mr-2"></i> Português
                </a>
                <a href="#" class="dropdown-item @if(\Illuminate\Support\Facades\Auth::user()->language == 'en') active @endif">
                    <i class="flag-icon flag-icon-us mr-2"></i> English
                </a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                <i class="fas fa-expand-arrows-alt"></i>
            </a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="fas fa-user"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <a class="dropdown-item" href="{{ route('profile.edit') }}">{{ __("general.menu.my_profile") }}</a>
                <a class="dropdown-item"
                   href="{{ route('user_groups.index') }}">{{ __("profile.user_groups.title") }}</a>
                <a class="dropdown-item" href="{{ route('logout') }}"
                   onclick="event.preventDefault();
                          document.getElementById('logout-form').submit();">
                    {{ __('general.menu.logout') }}
                </a>
            </div>
        </li>
    </ul>
</nav>
<!-- End Navbar -->