routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => 'auth'], function () {

    Route::get('/', function () {
        return view('home');
    });

    Route::get('home', 'App\Http\Controllers\HomeController@index')->name('home');
    Route::get('/', 'App\Http\Controllers\HomeController@index');
    Route::resource('wallets', 'App\Http\Controllers\WalletController');
    Route::resource('banks', 'App\Http\Controllers\BankController');
    Route::resource('credit_parcels', 'App\Http\Controllers\CreditParcelsController');
    Route::resource('expenses', 'App\Http\Controllers\ExpenseController');
    Route::resource('budgets', 'App\Http\Controllers\BudgetController');
    Route::resource('incomes', 'App\Http\Controllers\IncomeController');
    Route::resource('user_groups', 'App\Http\Controllers\UserGroupController');
    Route::resource('transfers', '\App\Http\Controllers\TransferController');
    Route::resource('investments', '\App\Http\Controllers\InvestmentController');
    Route::resource('invoices', '\App\Http\Controllers\InvoiceController');
    Route::resource('user', 'App\Http\Controllers\UserController', ['except' => ['show']]);
    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'App\Http\Controllers\ProfileController@edit']);
    Route::put('profile', ['as' => 'profile.update', 'uses' => 'App\Http\Controllers\ProfileController@update']);
    Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'App\Http\Controllers\ProfileController@password']);
    Route::post('profile/settings', ['as' => 'profile.settings', 'uses' => 'App\Http\Controllers\ProfileController@settings']);
    Route::get('{page}', ['as' => 'page.index', 'uses' => 'App\Http\Controllers\PageController@index']);
    Route::post('incomes/cancel_rec/{id}', 'App\Http\Controllers\IncomeController@cancel_rec')->name('incomes.cancel_rec');
    Route::get('incomes/confirm_recepit/{id}', 'App\Http\Controllers\IncomeController@confirm_recepit')->name('incomes.confirm_recepit');
    Route::get('user_groups/get_in/{group_id}/{user_id}', 'App\Http\Controllers\UserGroupController@GetInGroup')->name('user_groups.get_in');
    Route::get('user_groups/get_out/{group_id}/{user_id}', 'App\Http\Controllers\UserGroupController@GetOutGroup')->name('user_groups.get_out');
    Route::post('user_groups/remove_user/{group_id}/{user_id}', 'App\Http\Controllers\UserGroupController@remove_user')->name('user_groups.remove_user');
    Route::post('investments/insert_yield/{id}', 'App\Http\Controllers\InvestmentController@insert_yield')->name('investments.insert_yield');
    Route::post('budgets/default_budget', 'App\Http\Controllers\BudgetController@default_budget')->name('budgets.default_budget');
    Route::post('budgets/deactivate/{id}', 'App\Http\Controllers\BudgetController@disable')->name('budgets.disable');
    Route::post('budgets/reactivate/{id}', 'App\Http\Controllers\BudgetController@enable')->name('budgets.enable');
});

app/Models/Bank.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Bank extends Model
{
    use HasFactory;

    protected $fillable = [
        'user_id',
        'status',
        'name',
        'wallet_id',
        'f_deb',
        'f_cred',
        'f_invest'
    ];

    public function wallet()
    {
        return $this->belongsTo(Wallet::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function group()
    {
        return $this->belongsTo(UserGroup::class);
    }

    public function credit_parcels()
    {
        return $this->hasMany(CreditParcels::class, 'bank_id');
    }

    public function credit_card()
    {
        return $this->hasMany(CreditCard::class, 'bank_id');
    }
}

app/Http/Controllers/BankController.php
<?php

namespace App\Http\Controllers;

use App\Models\Bank;
use App\Models\CreditCard;
use App\Models\CreditParcels;
use App\Models\Expense;
use App\Models\Wallet;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class BankController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $banks = Bank::where(function ($query) {
            $query->where('user_id', Auth::user()->id)
                ->orWhereIn('group_id', explode(" ",Auth::user()->group_id));
        })
            ->get();

        return view('banks.index', compact('banks'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $wallets = Wallet::where(function ($query) {
            $query->where('user_id', Auth::user()->id)
                ->orWhereIn('group_id', explode(" ",Auth::user()->group_id));
        })
            ->where('status', 1)
            ->get();

        return view('banks.create', compact('wallets'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $user = Auth::user()->id;
        $f_deb = NULL;
        $f_cred = NULL;
        $f_invest = NULL;

        $request->validate([
            'name' => 'required',
            'wallet_id' => 'required'
        ]);

        if(Auth::user()->group_id != NULL){
            $group_id = Auth::user()->group_id;
        }else
        {
            $group_id = NULL;
        }

        $bank = Bank::create($request->all() + [
                'user_id' => $user,
                'f_deb' => $f_deb,
                'f_cred' => $f_cred,
                'f_invest' => $f_invest,
                'group_id' => $group_id
            ]);

        if ($request->input('f_cred')) {
            CreditCard::create([
                'bank_id' => $bank->id,
                'due_date' => $request->input('due_date'),
                'close_invoice' => $request->input('close_invoice'),
                'credit_limit' => $request->input('credit_limit'),
            ]);
        }

        return redirect()->route('banks.index')
            ->with('success', 'Banco/Conta registrada com sucesso!');
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Models\Bank $bank
     * @return \Illuminate\Http\Response
     */
    public function show(Bank $bank, CreditCard $creditCard)
    {
        //
        $now = Carbon::now();
        $today = $now->format('Y-m-d');
        $thisMonth = $now->format('m');
        $prevMonth = $now->subMonth()->format('m');
        $thisYear = $now->format('Y');

        if ($thisMonth != 1) {
            $prevYear = $now->format('Y');
        } else {
            $prevYear = $now->subYear()->format('Y');
        }

        $cc_info = CreditCard::where('bank_id', $bank->id);

        $start_date = $now->startOfMonth()->setDay($cc_info->value('close_invoice'))->format('Y-m-d');
        $end_date = $now->startOfMonth()->addMonth()->setDay($cc_info->value('close_invoice'))->format('Y-m-d');

        $cc_parcels = CreditParcels::where('bank_id', $bank->id)
            ->whereBetween('date', [$start_date, $end_date])
            //->unique('expense_id');
            ->get();

        $cc_expenses = Expense::where([
            ['bank_id', $bank->id],
            ['payment_method', 1],
            ['parcels', NULL]
        ])
            ->whereBetween('date', [$start_date, $end_date])
            ->get();

        $invoice_this_month = ($cc_parcels->sum('parcel_vl') + $cc_expenses->sum('value'));


        return view('banks.creditcard_details', compact('bank', 'cc_info', 'creditCard', 'cc_parcels', 'cc_expenses', 'invoice_this_month'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\Bank $bank
     * @return \Illuminate\Http\Response
     */
    public function edit(Bank $bank)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Bank $bank
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Bank $bank)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Bank $bank
     * @return \Illuminate\Http\Response
     */
    public function destroy(Bank $bank)
    {
        //
    }
}

resources/views/banks/create.blade.php
@extends('layouts.app', [
    'class' => 'sidebar-mini ',
    'namePage' => __('general.menu.banks') ." / ". __('general.menu.accounts'),
    'activePage' => 'banks',
    'activeNav' => '',
])

@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>{{__('general.menu.banks') ." / ". __('general.menu.accounts')}}</h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="card-tools">
                                <a href="{{route('banks.index')}}"
                                   class="btn btn-sm btn-info">{{__("general.menu.go_back")}}</a>
                            </div>
                        </div>
                        <div class="card-body">
                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <strong>Whoops!</strong> There were some problems with your input.<br><br>
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                            <form method="post" action="{{ route('banks.store') }}" autocomplete="off">
                                @csrf
                                @method('post')
                                @include('alerts.success')
                                <div class="row">
                                    <div class="col-md-6 pr-1">
                                        <div class="form-group">
                                            <label for="name">{{__("general.name")}}</label>
                                            <input type="text" name="name" class="form-control"
                                                   value="{{ old('name') }}" autocomplete="none">
                                            @include('alerts.feedback', ['field' => 'name'])
                                        </div>
                                    </div>
                                    <div class="col-md-6 pr-1">
                                        <div class="form-group">
                                            <label for="wallet_id">{{__("general.wallet")}}</label>
                                            <select id="wallet_id" name="wallet_id" class="form-control">
                                                <option class="disabled">--- {{__("general.menu.select")}}---</option>
                                                @foreach($wallets as $value)
                                                    <option value="{{$value->id}}">
                                                        {{$value->name}}
                                                        -
                                                        {{__("general.owner")}}
                                                        :
                                                        {{$value->user->name}} </option>
                                                @endforeach
                                            </select>
                                            @include('alerts.feedback', ['field' => 'wallet_id'])
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6 pr-1">
                                        <div class="form-group">
                                            <label for="payment_method">{{__("expenses.payment_mode")}}
                                                / {{__("bank.functions")}}</label>
                                            <div>
                                                <input type="checkbox" id="f_deb" name="f_deb" value="1">
                                                <label for="f_deb">{{__("general.debit")}}</label>
                                                <br>
                                                <input type="checkbox" id="f_cred" name="f_cred" value="1">
                                                <label for="f_cred">{{__("general.credit")}}</label>
                                                <br>
                                                <input type="checkbox" id="f_invest" name="f_invest" value="1">
                                                <label for="f_invest">{{__("general.investment")}}</label>
                                            </div>
                                            @include('alerts.feedback', ['field' => 'payment_method'])
                                        </div>
                                    </div>
                                </div>
                                <div class="row" id="show_cred" style="display:none">
                                    <div class="col-md-12">
                                        <div class="card">
                                            <div class="card-header">
                                                <h5 class="card-title">{{__('bank.credit_card_info')}}</h5>
                                            </div>
                                            <div class="card-body">
                                                <div class="col-md-4 pr-1">
                                                    <div class="form-group">
                                                        <label for="due_date">{{__("bank.due_date")}}</label>
                                                        <input type="number" name="due_date" class="form-control"
                                                               value="{{ old('due_date') }}">
                                                        @include('alerts.feedback', ['field' => 'due_date'])
                                                    </div>
                                                </div>
                                                <div class="col-md-4 pr-1">
                                                    <div class="form-group">
                                                        <label for="close_invoice">{{__("bank.close_invoice")}}</label>
                                                        <input type="number" name="close_invoice" class="form-control"
                                                               value="{{ old('close_invoice') }}">
                                                        @include('alerts.feedback', ['field' => 'close_invoice'])
                                                    </div>
                                                </div>
                                                <div class="col-md-4 pr-1">
                                                    <div class="form-group">
                                                        <label for="credit_limit">{{__("bank.credit_limit")}}</label>
                                                        <input type="number" min="1" step="any" name="credit_limit"
                                                               class="form-control" value="{{ old('credit_limit') }}">
                                                        @include('alerts.feedback', ['field' => 'credit_limit'])
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                        <hr class="half-rule"/>

                                        <button type="submit" class="btn btn-success">
                                            {{__('general.menu.save')}}
                                        </button>


                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection
@section('scripts')
    <script type="application/javascript">
        $(document).ready(function () {
            $('#f_cred').change(function () {
                $('#show_cred').toggle();
            });
        });
    </script>
@endsection

resources/views/banks/creditcard_details.blade.php
@extends('layouts.app', [
    'class' => 'sidebar-mini ',
    'namePage' => __('bank.credit_card_details'),
    'activePage' => 'banks',
    'activeNav' => '',
])

@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>{{$cc_info->first()->bank->name}}</h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">{{__('bank.credit_card_info')}}</h3>
                            <div class="card-tools">
                                <a href="{{route('banks.index')}}"
                                   class="btn btn-sm btn-info">{{__("general.menu.go_back")}}</a>
                            </div>
                        </div>
                        <div class="card-body">
                            @foreach($cc_info->get() as $value)
                                <b>{{__("bank.credit_limit")}}
                                    :</b> {{__('general.M_s') ." ".number_format($value->credit_limit, 2)}}
                                <br>

                                <b>{{__("bank.close_invoice")}}
                                    :</b> {{__('general.every_day') ." ".$value->close_invoice}}
                                <br>

                                <b>{{__("bank.due_date")}}:</b>  {{__('general.every_day') ." ".$value->due_date}}
                                <br>
                            @endforeach
                            <hr>
                            <div class="text-center">
                                <b>{{__('bank.invoice_this_month')}}</b>
                                <br>
                                {{__('general.M_s') ." ".number_format($invoice_this_month, 2)}}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">{{__('bank.credit_card_parcels')}}</h3>
                        </div>
                        <div class="card-body p-0">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead class="text-primary">
                                    <th>
                                        {{__("bank.due_date")}}
                                    </th>
                                    <th>
                                        {{__("bank.credit_parcels.parcel_value")}}
                                    </th>
                                    <th>
                                        {{__("general.details")}}
                                    </th>
                                    </thead>
                                    <tbody>
                                    @foreach($cc_parcels as $value)
                                        <tr>
                                            <td>
                                                {{$value->date->format('d/m/Y')}}
                                            </td>
                                            <td>
                                                {{__('general.M_s') ." ".number_format($value->parcel_vl, 2)}}
                                            </td>
                                            <td>
                                                {{$value->expense->details}}
                                            </td>

                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">{{__('bank.credit_card_expenses')}}</h3>
                        </div>
                        <div class="card-body p-0">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead class=" text-primary">
                                    <th>
                                        {{__("general.date")}}
                                    </th>
                                    <th>
                                        {{__("bank.credit_parcels.parcel_value")}}
                                    </th>
                                    <th>
                                        {{__("general.details")}}
                                    </th>
                                    </thead>
                                    <tbody>
                                    @foreach($cc_expenses as $value)
                                        <tr>
                                            <td>
                                                {{$value->date->format('d/m/Y')}}
                                            </td>
                                            <td>
                                                {{__('general.M_s') ." ".number_format($value->value, 2)}}
                                            </td>
                                            <td>
                                                {{$value->details}}
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/banks/index.blade.php
@extends('layouts.app', [
    'class' => 'sidebar-mini ',
    'namePage' => __('general.menu.banks') ." / ". __('general.menu.accounts'),
    'activePage' => 'banks',
    'activeNav' => '',
])

@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>{{__('bank.title')}}</h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h5 class="card-title">{{__("general.menu.banks")}} / {{__("general.menu.accounts")}}</h5>
                            <div class="card-tools">
                                <a href="{{route('banks.create')}}"
                                   class="btn btn-sm btn-info">{{__("bank.create_new")}}</a>
                            </div>
                        </div>
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                        <div class="card-body p-0">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead class=" text-primary">
                                    <th>
                                        {{__("general.name")}}
                                    </th>
                                    <th>
                                        {{__("bank.functions")}}
                                    </th>
                                    <th>
                                        {{__("general.wallet")}} / {{__("general.info.belong_to")}}
                                    </th>
                                    <th>
                                        {{__("general.group")}}
                                    </th>
                                    </thead>
                                    <tbody>
                                    @foreach($banks as $value)
                                        <tr>
                                            <td>
                                                {{$value->name}}
                                            </td>
                                            <td>
                                                {{$value->payment_method}}
                                                @if($value->f_deb != NULL)
                                                    <b title="{{__("general.debit")}}">D</b>
                                                @endif
                                                @if($value->f_cred != NULL)
                                                    <a href="{{route('banks.show', $value->id)}}">
                                                        <b title="{{__("general.credit")}}">C</b>
                                                    </a>
                                                @endif
                                                @if($value->f_invest != NULL)
                                                    <b title="{{__("general.investment")}}">I</b>
                                                @endif
                                            </td>
                                            <td>
                                                @if($value->wallet_id == NULL)
                                                    <i class="text-danger">
                                                        <b>{{__("account.inactive")}}</b>
                                                    </i>
                                                @else
                                                    <b>{{$value->wallet->name}}</b> - {{$value->user->name}}
                                                @endif

                                            </td>
                                            <td>
                                                @if($value->group_id == NULL)
                                                    <small>{{__("general.no_group")}}</small>
                                                @else
                                                    {{$value->group->name}}
                                                @endif
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection