routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => 'auth'], function () {

    Route::get('/', function () {
        return view('home');
    });

    Route::get('home', 'App\Http\Controllers\HomeController@index')->name('home');
    Route::get('/', 'App\Http\Controllers\HomeController@index');
    Route::resource('wallets', 'App\Http\Controllers\WalletController');
    Route::resource('banks', 'App\Http\Controllers\BankController');
    Route::resource('credit_parcels', 'App\Http\Controllers\CreditParcelsController');
    Route::resource('expenses', 'App\Http\Controllers\ExpenseController');
    Route::resource('budgets', 'App\Http\Controllers\BudgetController');
    Route::resource('incomes', 'App\Http\Controllers\IncomeController');
    Route::resource('user_groups', 'App\Http\Controllers\UserGroupController');
    Route::resource('transfers', '\App\Http\Controllers\TransferController');
    Route::resource('investments', '\App\Http\Controllers\InvestmentController');
    Route::resource('invoices', '\App\Http\Controllers\InvoiceController');
    Route::resource('user', 'App\Http\Controllers\UserController', ['except' => ['show']]);
    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'App\Http\Controllers\ProfileController@edit']);
    Route::put('profile', ['as' => 'profile.update', 'uses' => 'App\Http\Controllers\ProfileController@update']);
    Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'App\Http\Controllers\ProfileController@password']);
    Route::post('profile/settings', ['as' => 'profile.settings', 'uses' => 'App\Http\Controllers\ProfileController@settings']);
    Route::get('{page}', ['as' => 'page.index', 'uses' => 'App\Http\Controllers\PageController@index']);
    Route::post('incomes/cancel_rec/{id}', 'App\Http\Controllers\IncomeController@cancel_rec')->name('incomes.cancel_rec');
    Route::get('incomes/confirm_recepit/{id}', 'App\Http\Controllers\IncomeController@confirm_recepit')->name('incomes.confirm_recepit');
    Route::get('user_groups/get_in/{group_id}/{user_id}', 'App\Http\Controllers\UserGroupController@GetInGroup')->name('user_groups.get_in');
    Route::get('user_groups/get_out/{group_id}/{user_id}', 'App\Http\Controllers\UserGroupController@GetOutGroup')->name('user_groups.get_out');
    Route::post('user_groups/remove_user/{group_id}/{user_id}', 'App\Http\Controllers\UserGroupController@remove_user')->name('user_groups.remove_user');
    Route::post('investments/insert_yield/{id}', 'App\Http\Controllers\InvestmentController@insert_yield')->name('investments.insert_yield');
    Route::post('budgets/default_budget', 'App\Http\Controllers\BudgetController@default_budget')->name('budgets.default_budget');
    Route::post('budgets/deactivate/{id}', 'App\Http\Controllers\BudgetController@disable')->name('budgets.disable');
    Route::post('budgets/reactivate/{id}', 'App\Http\Controllers\BudgetController@enable')->name('budgets.enable');
});

app/Models/Income.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Income extends Model
{
    use HasFactory;

    protected $casts = [
        'value' => 'float',
        'rec_income' => 'integer'
    ];

    protected $dates = [
        'date'
    ];

    protected $fillable = [
        'org_id',
        'group_id',
        'user_id',
        'date',
        'value',
        'bank_id',
        'rec_income',
        'details'
    ];

    public function bank()
    {
        return $this->belongsTo(Bank::class);
    }

    public function wallet()
    {
        return $this->belongsTo(Wallet::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/IncomeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Bank;
use App\Models\Income;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class IncomeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $incomes = Income::where(function ($query) {
            $query->where('user_id', Auth::user()->id)
                ->orWhereIn('group_id', explode(" ", Auth::user()->group_id));
        })
            ->orderBy('date', 'desc')
            ->get();
        return view('incomes.index', compact('incomes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $banks = Bank::where(function ($query) {
            $query->where('user_id', Auth::user()->id)
                ->orWhereIn('group_id', explode(" ", Auth::user()->group_id));
        })
            ->where('wallet_id', '!=', 0)
            ->get();

        return view('incomes.create', compact('banks'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $user = Auth::user()->id;

        $request->validate([
            'date' => 'required',
            'value' => 'required',
            'bank_id' => 'required'
        ]);

        $income = Income::create($request->all() + ['user_id' => $user]);
        if (Auth::user()->group_id != NULL) {
            $income->group_id = Auth::user()->group_id;
        }
        $income->org_id = $income->id;
        $income->save();

        return redirect()->route('incomes.index')
            ->with('success', 'Despesa registrada com sucesso!');
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Models\Income $income
     * @return \Illuminate\Http\Response
     */
    public function show(Income $income)
    {
        //
        $income_details = Income::where('id', $income->id)->get();
        return view('incomes.details', compact('income', 'income_details'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\Income $income
     * @return \Illuminate\Http\Response
     */
    public function edit(Income $income)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Income $income
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Income $income)
    {
        //
    }

    /**
     * Cancel the recurency update in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Income $income
     * @return \Illuminate\Http\Response
     */
    public function cancel_rec($id)
    {
        //
        Income::where('org_id', $id)
            ->update(['rec_income' => NULL]);

        return redirect()->route('incomes.index')
            ->with('message', 'Recurrency canceled');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Income $income
     * @return \Illuminate\Http\Response
     */
    public function destroy(Income $income)
    {
        //
    }

    public function confirm_recepit($id)
    {
        Income::where('org_id', $id)
            ->update(['confirmed' => 1]);

        return redirect()->route('incomes.index')
            ->with('message', 'Income confirmed!');
    }
}

resources/views/incomes/create.blade.php
@extends('layouts.app', [
    'class' => 'sidebar-mini ',
    'namePage' => __('incomes.title'). " / " .__('general.menu.create'),
    'activePage' => 'incomes',
    'activeNav' => '',
])

@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>{{__('incomes.title')}}</h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <a href="{{route('incomes.index')}}"
                           class="btn btn-sm btn-info">{{__("general.menu.go_back")}}</a>
                    </div>
                    <div class="card-body">
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                        <form method="post" action="{{ route('incomes.store') }}" autocomplete="off">
                            @csrf
                            @method('post')
                            @include('alerts.success')
                            <div class="row">
                            </div>
                            <div class="row">
                                <div class="col-md-4 pr-1">
                                    <div class="form-group">
                                        <label for="date">{{__("general.date")}}</label>
                                        <input type="date" name="date" class="form-control"
                                               value="{{ old('date') ?? date('Y-m-d')}}">
                                        @include('alerts.feedback', ['field' => 'date'])
                                    </div>
                                </div>
                                <div class="col-md-4 pr-1">
                                    <div class="form-group">
                                        <label for="value">{{__("general.value")}}</label>
                                        <input type="number" min="1" step="any" name="value" id="value"
                                               class="form-control" value="{{ old('value') }}" oninput="calc();">
                                        @include('alerts.feedback', ['field' => 'value'])
                                    </div>
                                </div>
                                <div class="col-md-4 pr-1">
                                    <div class="form-group">
                                        <label for="bank_id">{{__("general.bank")}} / {{__("general.account")}}</label>
                                        <select id="bank_id" name="bank_id" class="form-control">
                                            <option value=""> --- {{__("general.menu.select")}} ---</option>
                                            @foreach($banks as $value)
                                                <option value="{{$value->id}}"><b>{{$value->name}}</b>
                                                    - {{$value->payment_method}} ({{$value->wallet->name}})
                                                </option>
                                            @endforeach
                                        </select>
                                        @include('alerts.feedback', ['field' => 'bank_id'])
                                    </div>
                                </div>
                            </div>
                            <hr class="half-rule"/>
                            <div class="row">
                                <div class="col-md-12 pr-1">
                                    <div class="form-group">
                                        <label for="details">{{__("general.details")}}</label>
                                        <textarea name="details" class="form-control"
                                                  value="{{ old('details') }}"></textarea>
                                        @include('alerts.feedback', ['field' => 'details'])
                                    </div>
                                </div>
                            </div>

                            <input type="checkbox" id="rec_income" name="rec_income" value="1">
                            <label for="rec_income">{{__("incomes.recurring")}}</label>

                            <hr>
                            <button type="submit" class="btn btn-success">{{__('general.menu.save')}}</button>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>

@endsection

resources/views/incomes/details.blade.php
@extends('layouts.app', [
'class' => 'sidebar-mini ',
'namePage' => __('incomes.title'). " / " .__('general.details'),
'activePage' => 'incomes',
'activeNav' => '',
])

@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>{{__('incomes.title')}}</h1>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        <h5 class="title">{{__('general.details')}} <small> ID: {{$income->id}}</small></h5>
                    </div>
                    <div class="card-tools">
                        <a href="{{route('incomes.index')}}" class="btn btn-sm btn-info">{{__("general.menu.go_back")}}</a>
                    </div>
                </div>
                @if ($errors->any())
                <div class="alert alert-danger">
                    <strong>Whoops!</strong> There were some problems with your input.<br><br>
                    <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                @endif
                <div class="card-body">

                    @foreach($income_details as $value)
                    {{__("general.date")}}: {{$value->date->format('d/m/Y')}}
                    <br>
                    {{__("general.value")}}: {{__('general.M_s') . " " . number_format($value->value, 2)}}
                    @if($value->rec_income)
                    <small>
                        <i class="fas fa-sync-alt" title="{{__("incomes.recurring")}}"></i>
                    </small>
                    @endif
                    <br>
                    {{__("general.bank")}}/{{__("general.account")}}: <b>{{$value->bank->name}}</b>
                    - {{$value->bank->payment_method}} ({{$value->bank->wallet->name}})
                    <br>
                    <hr>
                    <b>{{ __('general.details') }}</b>
                    <br>
                    {{ $value->details }}
                    <hr>
                    <p class="pull-right">
                        {{__("general.info.registred_by")}}: {{$value->user->name}}
                        <br>
                        {{__("general.info.registred_at")}}: {{$value->created_at->format('d/m/Y H:m')}}
                    </p>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/incomes/index.blade.php
@extends('layouts.app', [
'class' => 'sidebar-mini ',
'namePage' => __('incomes.title'),
'activePage' => 'incomes',
'activeNav' => '',
])

@section('content')

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>{{__('incomes.title')}}</h1>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <a href="{{route('incomes.create')}}" class="btn btn-sm btn-info">{{__("incomes.create_new")}}</a>
                </div>
                @if(session()->has('message'))
                <div class="alert alert-success">
                    {{ session()->get('message') }}
                </div>
                @endif
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table">
                            <thead class=" text-primary">
                                <th>
                                    {{__("general.date")}}
                                </th>
                                <th>
                                    {{__("general.value")}}
                                </th>
                                <th>
                                    {{__("general.details")}}
                                </th>
                                <th>
                                    {{__("general.wallet")}} / {{__("general.account")}}
                                </th>
                                <th style="width: 20%">

                                </th>
                            </thead>
                            <tbody>
                                @foreach($incomes as $value)
                                <tr>
                                    <td>
                                        {{$value->date->format('d/m/Y')}}
                                    </td>
                                    <td>
                                        {{__('general.M_s')}} {{number_format($value->value, 2)}}
                                        @if($value->rec_income)
                                        <small>
                                            <i class="fas fa-sync-alt" title="{{__("incomes.recurring")}}"></i>
                                        </small>
                                        @endif
                                    </td>
                                    <td>
                                        {{ $value->details }}
                                    </td>
                                    <td>
                                        <b>{{$value->bank->name}}</b> ({{$value->bank->wallet->name}})
                                    </td>
                                    <td>
                                        @if($value->confirmed == 0)
                                        <a style="color: green;" href="{{route('incomes.confirm_recepit', $value->id)}}">
                                            {{__('incomes.confirm_receipt')}}
                                        </a>
                                        <br>
                                        @endif
                                        <form action="{{ route('incomes.cancel_rec',$value->org_id) }}" method="POST">
                                            <a href="{{route('incomes.show', $value->id)}}">{{__('general.details')}}</a>
                                            <br>
                                            @csrf
                                            @method('POST')
                                            <a type="submit" style="color: red">{{__('incomes.cancel_rec')}}</a>
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


@if ($errors->any())
<div class="toasts-top-right fixed">
    <div class="toast bg-danger fade show" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="toast-header">
            <strong class="mr-auto">{{__('messages.attention')}}</strong>
            <button data-dismiss="toast" type="button" class="ml-2 mb-1 close" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
        </div>
        <div class="toast-body">
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </div>
    </div>
</div>
@endif
@endsection